AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

plugins:
  - rubocop-performance
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Max: 300

Layout/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Metrics/ModuleLength:
  Max: 200