AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

plugins:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/support/generate_test_pdfs.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'spec/support/generate_test_pdfs.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'spec/support/generate_test_pdfs.rb'

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - 'spec/support/generate_test_pdfs.rb'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'spec/support/generate_test_pdfs.rb'

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes